### PR TITLE
Bump up versions used and remove Poison dependency

### PR DESCRIPTION
**Pull request by filipecabaco**
Removed Poison dependency by bumping up oauth2 dependency and adding setting the JSON client of OAuth using Ueberauth's `json_library()` function.

Refer to https://github.com/ueberauth/ueberauth_facebook/pull/48

### CODE REVIEW

**Comment by filipecabaco** [comment]
Unsure about it but this could be a breaking change. It might need a bump in minor

**Comment by maxbeizer** [comment]
Thanks for the PR @filipecabaco ! I'll be taking a look later today

**Comment by filipecabaco** [comment]
Hi 👋 wondering if this could be merged 🙏

**Comment by maxbeizer** [comment]
@filipecabaco oh my. I'm really sorry this slipped my mind 🙇

**Review by maxbeizer — APPROVED** [review]

**Comment by maxbeizer** [comment]
I'll try to cut a new release ASAP

**Comment by filipecabaco** [comment]
Oh no worries! Didn't want to rush you just wanted to have an idea 

Nonetheless, thank you for the help 🙏

**Comment by maxbeizer** [comment]
@filipecabaco https://hexdocs.pm/ueberauth_heroku/0.3.0/api-reference.html is out. Thanks for your patience and sorry again about the delay

**Comment by filipecabaco** [comment]
Don't be sorry, I am for rushing you. Thank you for the availability, time, and code 🙏

**Pull request merged**
